# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chenyansu/code/scrapyd_manager/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 544)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 571, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.scrapyd = QtWidgets.QWidget()
        self.scrapyd.setObjectName("scrapyd")
        self.running_spider_comboBox = QtWidgets.QComboBox(self.scrapyd)
        self.running_spider_comboBox.setGeometry(QtCore.QRect(100, 390, 411, 27))
        self.running_spider_comboBox.setObjectName("running_spider_comboBox")
        self.project_name_comboBox = QtWidgets.QComboBox(self.scrapyd)
        self.project_name_comboBox.setGeometry(QtCore.QRect(100, 330, 411, 27))
        self.project_name_comboBox.setObjectName("project_name_comboBox")
        self.del_project_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.del_project_pushButton.setGeometry(QtCore.QRect(460, 430, 81, 26))
        self.del_project_pushButton.setObjectName("del_project_pushButton")
        self.label = QtWidgets.QLabel(self.scrapyd)
        self.label.setGeometry(QtCore.QRect(20, 330, 71, 17))
        self.label.setObjectName("label")
        self.show_message_textBrowser = QtWidgets.QTextBrowser(self.scrapyd)
        self.show_message_textBrowser.setGeometry(QtCore.QRect(10, 0, 541, 231))
        self.show_message_textBrowser.setObjectName("show_message_textBrowser")
        self.spider_name_comboBox = QtWidgets.QComboBox(self.scrapyd)
        self.spider_name_comboBox.setGeometry(QtCore.QRect(100, 360, 411, 27))
        self.spider_name_comboBox.setObjectName("spider_name_comboBox")
        self.start_spider_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.start_spider_pushButton.setGeometry(QtCore.QRect(10, 430, 91, 26))
        self.start_spider_pushButton.setObjectName("start_spider_pushButton")
        self.label_3 = QtWidgets.QLabel(self.scrapyd)
        self.label_3.setGeometry(QtCore.QRect(20, 390, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.scrapyd)
        self.label_2.setGeometry(QtCore.QRect(20, 360, 67, 17))
        self.label_2.setObjectName("label_2")
        self.server_select_comboBox = QtWidgets.QComboBox(self.scrapyd)
        self.server_select_comboBox.setGeometry(QtCore.QRect(100, 250, 311, 27))
        self.server_select_comboBox.setObjectName("server_select_comboBox")
        self.label_4 = QtWidgets.QLabel(self.scrapyd)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 71, 17))
        self.label_4.setObjectName("label_4")
        self.refresh_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.refresh_pushButton.setGeometry(QtCore.QRect(440, 460, 97, 26))
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.server_del_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.server_del_pushButton.setGeometry(QtCore.QRect(416, 250, 121, 26))
        self.server_del_pushButton.setObjectName("server_del_pushButton")
        self.kill_spider_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.kill_spider_pushButton.setGeometry(QtCore.QRect(250, 430, 91, 26))
        self.kill_spider_pushButton.setObjectName("kill_spider_pushButton")
        self.label_9 = QtWidgets.QLabel(self.scrapyd)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 51, 21))
        self.label_9.setObjectName("label_9")
        self.pending_lcdNumber = QtWidgets.QLCDNumber(self.scrapyd)
        self.pending_lcdNumber.setGeometry(QtCore.QRect(80, 290, 64, 23))
        self.pending_lcdNumber.setObjectName("pending_lcdNumber")
        self.label_10 = QtWidgets.QLabel(self.scrapyd)
        self.label_10.setGeometry(QtCore.QRect(160, 290, 51, 21))
        self.label_10.setObjectName("label_10")
        self.running_lcdNumber = QtWidgets.QLCDNumber(self.scrapyd)
        self.running_lcdNumber.setGeometry(QtCore.QRect(220, 290, 64, 23))
        self.running_lcdNumber.setObjectName("running_lcdNumber")
        self.label_11 = QtWidgets.QLabel(self.scrapyd)
        self.label_11.setGeometry(QtCore.QRect(310, 290, 51, 21))
        self.label_11.setObjectName("label_11")
        self.finished_lcdNumber = QtWidgets.QLCDNumber(self.scrapyd)
        self.finished_lcdNumber.setGeometry(QtCore.QRect(370, 290, 64, 23))
        self.finished_lcdNumber.setObjectName("finished_lcdNumber")
        self.s_r_spider_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.s_r_spider_pushButton.setGeometry(QtCore.QRect(130, 430, 121, 26))
        self.s_r_spider_pushButton.setObjectName("s_r_spider_pushButton")
        self.line = QtWidgets.QFrame(self.scrapyd)
        self.line.setGeometry(QtCore.QRect(130, 460, 51, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.scrapyd)
        self.line_2.setGeometry(QtCore.QRect(280, 460, 51, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_12 = QtWidgets.QLabel(self.scrapyd)
        self.label_12.setGeometry(QtCore.QRect(186, 460, 91, 20))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.scrapyd, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.server_name_lineEdit = QtWidgets.QLineEdit(self.settings)
        self.server_name_lineEdit.setGeometry(QtCore.QRect(120, 20, 113, 27))
        self.server_name_lineEdit.setObjectName("server_name_lineEdit")
        self.server_address_lineEdit = QtWidgets.QLineEdit(self.settings)
        self.server_address_lineEdit.setGeometry(QtCore.QRect(250, 20, 171, 27))
        self.server_address_lineEdit.setObjectName("server_address_lineEdit")
        self.server_add_pushButton = QtWidgets.QPushButton(self.settings)
        self.server_add_pushButton.setGeometry(QtCore.QRect(440, 20, 51, 26))
        self.server_add_pushButton.setObjectName("server_add_pushButton")
        self.label_5 = QtWidgets.QLabel(self.settings)
        self.label_5.setGeometry(QtCore.QRect(6, 20, 101, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.settings)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.label_6.setObjectName("label_6")
        self.project_name_lineEdit = QtWidgets.QLineEdit(self.settings)
        self.project_name_lineEdit.setGeometry(QtCore.QRect(120, 50, 113, 27))
        self.project_name_lineEdit.setObjectName("project_name_lineEdit")
        self.project_address_lineEdit = QtWidgets.QLineEdit(self.settings)
        self.project_address_lineEdit.setGeometry(QtCore.QRect(250, 50, 171, 27))
        self.project_address_lineEdit.setObjectName("project_address_lineEdit")
        self.project_add_pushButton = QtWidgets.QPushButton(self.settings)
        self.project_add_pushButton.setGeometry(QtCore.QRect(440, 50, 51, 26))
        self.project_add_pushButton.setObjectName("project_add_pushButton")
        self.label_7 = QtWidgets.QLabel(self.settings)
        self.label_7.setGeometry(QtCore.QRect(0, 470, 91, 17))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.settings)
        self.lineEdit.setGeometry(QtCore.QRect(350, 470, 211, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.label_8 = QtWidgets.QLabel(self.settings)
        self.label_8.setGeometry(QtCore.QRect(100, 470, 161, 17))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.settings, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.del_project_pushButton.setText(_translate("MainWindow", "删除项目"))
        self.label.setText(_translate("MainWindow", "项目名称"))
        self.start_spider_pushButton.setText(_translate("MainWindow", "启动爬虫"))
        self.label_3.setText(_translate("MainWindow", "运行中"))
        self.label_2.setText(_translate("MainWindow", "爬虫名称"))
        self.label_4.setText(_translate("MainWindow", "服务器"))
        self.refresh_pushButton.setText(_translate("MainWindow", "刷新"))
        self.server_del_pushButton.setText(_translate("MainWindow", "删除当前服务器"))
        self.kill_spider_pushButton.setText(_translate("MainWindow", "杀死爬虫"))
        self.label_9.setText(_translate("MainWindow", "等待中"))
        self.label_10.setText(_translate("MainWindow", "运行中"))
        self.label_11.setText(_translate("MainWindow", "已完成"))
        self.s_r_spider_pushButton.setText(_translate("MainWindow", "暂停/恢复爬虫"))
        self.label_12.setText(_translate("MainWindow", "only for local"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scrapyd), _translate("MainWindow", "scrapyd"))
        self.server_name_lineEdit.setText(_translate("MainWindow", "name"))
        self.server_address_lineEdit.setText(_translate("MainWindow", "address"))
        self.server_add_pushButton.setText(_translate("MainWindow", "添加"))
        self.label_5.setText(_translate("MainWindow", "scrapyd服务器"))
        self.label_6.setText(_translate("MainWindow", "scrapyd项目"))
        self.project_name_lineEdit.setText(_translate("MainWindow", "name"))
        self.project_address_lineEdit.setText(_translate("MainWindow", "path"))
        self.project_add_pushButton.setText(_translate("MainWindow", "添加"))
        self.label_7.setText(_translate("MainWindow", "作者: 陈严肃"))
        self.lineEdit.setText(_translate("MainWindow", "https://github.com/chenyansu"))
        self.label_8.setText(_translate("MainWindow", "本软件遵守GPL V2 协议"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("MainWindow", "设置"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

