# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chenyansu/code/scrapyd_manager/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 544)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 571, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.scrapyd = QtWidgets.QWidget()
        self.scrapyd.setObjectName("scrapyd")
        self.project_version_comboBox = QtWidgets.QComboBox(self.scrapyd)
        self.project_version_comboBox.setGeometry(QtCore.QRect(100, 360, 411, 27))
        self.project_version_comboBox.setObjectName("project_version_comboBox")
        self.project_name_comboBox = QtWidgets.QComboBox(self.scrapyd)
        self.project_name_comboBox.setGeometry(QtCore.QRect(100, 330, 411, 27))
        self.project_name_comboBox.setObjectName("project_name_comboBox")
        self.get_spider_status_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.get_spider_status_pushButton.setGeometry(QtCore.QRect(140, 290, 141, 26))
        self.get_spider_status_pushButton.setObjectName("get_spider_status_pushButton")
        self.update_project_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.update_project_pushButton.setGeometry(QtCore.QRect(140, 430, 141, 26))
        self.update_project_pushButton.setObjectName("update_project_pushButton")
        self.del_project_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.del_project_pushButton.setGeometry(QtCore.QRect(410, 430, 131, 26))
        self.del_project_pushButton.setObjectName("del_project_pushButton")
        self.label = QtWidgets.QLabel(self.scrapyd)
        self.label.setGeometry(QtCore.QRect(20, 330, 71, 17))
        self.label.setObjectName("label")
        self.show_message_textBrowser = QtWidgets.QTextBrowser(self.scrapyd)
        self.show_message_textBrowser.setGeometry(QtCore.QRect(10, 0, 541, 231))
        self.show_message_textBrowser.setObjectName("show_message_textBrowser")
        self.spider_name_comboBox = QtWidgets.QComboBox(self.scrapyd)
        self.spider_name_comboBox.setGeometry(QtCore.QRect(100, 390, 411, 27))
        self.spider_name_comboBox.setObjectName("spider_name_comboBox")
        self.project_list_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.project_list_pushButton.setGeometry(QtCore.QRect(280, 290, 131, 26))
        self.project_list_pushButton.setObjectName("project_list_pushButton")
        self.spider_list_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.spider_list_pushButton.setGeometry(QtCore.QRect(410, 290, 131, 26))
        self.spider_list_pushButton.setObjectName("spider_list_pushButton")
        self.start_spider_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.start_spider_pushButton.setGeometry(QtCore.QRect(10, 430, 131, 26))
        self.start_spider_pushButton.setObjectName("start_spider_pushButton")
        self.label_3 = QtWidgets.QLabel(self.scrapyd)
        self.label_3.setGeometry(QtCore.QRect(20, 360, 67, 17))
        self.label_3.setObjectName("label_3")
        self.server_status_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.server_status_pushButton.setGeometry(QtCore.QRect(10, 290, 131, 26))
        self.server_status_pushButton.setObjectName("server_status_pushButton")
        self.del_spider_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.del_spider_pushButton.setGeometry(QtCore.QRect(280, 430, 131, 26))
        self.del_spider_pushButton.setObjectName("del_spider_pushButton")
        self.label_2 = QtWidgets.QLabel(self.scrapyd)
        self.label_2.setGeometry(QtCore.QRect(20, 390, 67, 17))
        self.label_2.setObjectName("label_2")
        self.server_select_comboBox = QtWidgets.QComboBox(self.scrapyd)
        self.server_select_comboBox.setGeometry(QtCore.QRect(100, 250, 311, 27))
        self.server_select_comboBox.setObjectName("server_select_comboBox")
        self.label_4 = QtWidgets.QLabel(self.scrapyd)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 71, 17))
        self.label_4.setObjectName("label_4")
        self.refresh_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.refresh_pushButton.setGeometry(QtCore.QRect(440, 460, 97, 26))
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.server_del_pushButton = QtWidgets.QPushButton(self.scrapyd)
        self.server_del_pushButton.setGeometry(QtCore.QRect(416, 250, 121, 26))
        self.server_del_pushButton.setObjectName("server_del_pushButton")
        self.tabWidget.addTab(self.scrapyd, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.scrapyd_server_name_lineEdit = QtWidgets.QLineEdit(self.settings)
        self.scrapyd_server_name_lineEdit.setGeometry(QtCore.QRect(120, 20, 113, 27))
        self.scrapyd_server_name_lineEdit.setObjectName("scrapyd_server_name_lineEdit")
        self.scrapyd_server_address_lineEdit = QtWidgets.QLineEdit(self.settings)
        self.scrapyd_server_address_lineEdit.setGeometry(QtCore.QRect(250, 20, 171, 27))
        self.scrapyd_server_address_lineEdit.setObjectName("scrapyd_server_address_lineEdit")
        self.scrapyd_server_add_pushButton = QtWidgets.QPushButton(self.settings)
        self.scrapyd_server_add_pushButton.setGeometry(QtCore.QRect(440, 20, 51, 26))
        self.scrapyd_server_add_pushButton.setObjectName("scrapyd_server_add_pushButton")
        self.label_5 = QtWidgets.QLabel(self.settings)
        self.label_5.setGeometry(QtCore.QRect(6, 20, 101, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.settings)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.label_6.setObjectName("label_6")
        self.scrapyd_project_name_lineEdit = QtWidgets.QLineEdit(self.settings)
        self.scrapyd_project_name_lineEdit.setGeometry(QtCore.QRect(120, 50, 113, 27))
        self.scrapyd_project_name_lineEdit.setObjectName("scrapyd_project_name_lineEdit")
        self.scrapyd_project_address_lineEdit = QtWidgets.QLineEdit(self.settings)
        self.scrapyd_project_address_lineEdit.setGeometry(QtCore.QRect(250, 50, 171, 27))
        self.scrapyd_project_address_lineEdit.setObjectName("scrapyd_project_address_lineEdit")
        self.scrapyd_server_add_pushButton_2 = QtWidgets.QPushButton(self.settings)
        self.scrapyd_server_add_pushButton_2.setGeometry(QtCore.QRect(440, 50, 51, 26))
        self.scrapyd_server_add_pushButton_2.setObjectName("scrapyd_server_add_pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.settings)
        self.label_7.setGeometry(QtCore.QRect(0, 470, 91, 17))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.settings)
        self.lineEdit.setGeometry(QtCore.QRect(350, 470, 211, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.label_8 = QtWidgets.QLabel(self.settings)
        self.label_8.setGeometry(QtCore.QRect(100, 470, 161, 17))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.settings, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.get_spider_status_pushButton.setText(_translate("MainWindow", "详细运行状态"))
        self.update_project_pushButton.setText(_translate("MainWindow", "更新项目"))
        self.del_project_pushButton.setText(_translate("MainWindow", "删除项目"))
        self.label.setText(_translate("MainWindow", "项目名称"))
        self.project_list_pushButton.setText(_translate("MainWindow", "项目清单"))
        self.spider_list_pushButton.setText(_translate("MainWindow", "爬虫清单"))
        self.start_spider_pushButton.setText(_translate("MainWindow", "启动爬虫"))
        self.label_3.setText(_translate("MainWindow", "项目版本"))
        self.server_status_pushButton.setText(_translate("MainWindow", "服务器运行状态"))
        self.del_spider_pushButton.setText(_translate("MainWindow", "删除项目版本"))
        self.label_2.setText(_translate("MainWindow", "爬虫名称"))
        self.label_4.setText(_translate("MainWindow", "服务器"))
        self.refresh_pushButton.setText(_translate("MainWindow", "刷新"))
        self.server_del_pushButton.setText(_translate("MainWindow", "删除当前服务器"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scrapyd), _translate("MainWindow", "scrapyd"))
        self.scrapyd_server_name_lineEdit.setText(_translate("MainWindow", "name"))
        self.scrapyd_server_address_lineEdit.setText(_translate("MainWindow", "address"))
        self.scrapyd_server_add_pushButton.setText(_translate("MainWindow", "添加"))
        self.label_5.setText(_translate("MainWindow", "scrapyd服务器"))
        self.label_6.setText(_translate("MainWindow", "scrapyd项目"))
        self.scrapyd_project_name_lineEdit.setText(_translate("MainWindow", "name"))
        self.scrapyd_project_address_lineEdit.setText(_translate("MainWindow", "path"))
        self.scrapyd_server_add_pushButton_2.setText(_translate("MainWindow", "添加"))
        self.label_7.setText(_translate("MainWindow", "作者: 陈严肃"))
        self.lineEdit.setText(_translate("MainWindow", "https://github.com/chenyansu"))
        self.label_8.setText(_translate("MainWindow", "本软件遵守GPL V2 协议"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("MainWindow", "设置"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

